graph LR
  AssociatesModule --> AppModule
  AttendanceModule --> AppModule
  AuthModule --> AppModule
  CaseDocumentsModule --> AppModule
  ExpensesModule --> AppModule
  ExpensesModule --> FixedExpensesModule
  ExpensesModule --> ManualExpensesModule
  ExpensesModule --> RecurringExpensesModule
  FirmsModule --> AppModule
  FixedExpensesModule --> AppModule
  HearingsModule --> AppModule
  LeaveModule --> AppModule
  ManualExpensesModule --> AppModule
  MattersModule --> AppModule
  MattersModule --> CaseDocumentsModule
  MattersModule --> HearingsModule
  PrismaModule --> AppModule
  PrismaModule --> AssociatesModule
  PrismaModule --> AttendanceModule
  PrismaModule --> AuthModule
  PrismaModule --> CaseDocumentsModule
  PrismaModule --> ExpensesModule
  PrismaModule --> FirmsModule
  PrismaModule --> FixedExpensesModule
  PrismaModule --> HearingsModule
  PrismaModule --> LeaveModule
  PrismaModule --> ManualExpensesModule
  PrismaModule --> MattersModule
  PrismaModule --> RecurringExpensesModule
  PrismaModule --> TasksModule
  PrismaModule --> UsersModule
  RecurringExpensesModule --> AppModule
  TasksModule --> AppModule
  UsersModule --> AppModule
  UsersModule --> AssociatesModule
  UsersModule --> AttendanceModule
  UsersModule --> MattersModule
  UsersModule --> TasksModule
