graph LR
  AssociatesModule --> AppModule
  AttendanceModule --> AppModule
  AuthModule --> AppModule
  FirmsModule --> AppModule
  FixedExpensesModule --> AppModule
  LeaveModule --> AppModule
  ManualExpensesModule --> AppModule
  PrismaModule --> AppModule
  PrismaModule --> AssociatesModule
  PrismaModule --> AttendanceModule
  PrismaModule --> AuthModule
  PrismaModule --> FirmsModule
  PrismaModule --> FixedExpensesModule
  PrismaModule --> LeaveModule
  PrismaModule --> ManualExpensesModule
  PrismaModule --> UsersModule
  UsersModule --> AppModule
  UsersModule --> AssociatesModule
  UsersModule --> AttendanceModule
